# Generated by Django 5.1.6 on 2025-02-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
